"""drop_acceptance_criteria_scope_prompt

Revision ID: 5faf4e4f5d6a
Revises: 004
Create Date: 2026-06-01 20:42:20.578541
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5faf4e4f5d6a"
down_revision = "004"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tickets", "prompt")
    op.drop_column("tickets", "acceptance_criteria")
    op.drop_column("tickets", "scope")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickets", sa.Column("scope", sa.TEXT(), nullable=True))
    op.add_column("tickets", sa.Column("acceptance_criteria", sa.TEXT(), nullable=True))
    op.add_column("tickets", sa.Column("prompt", sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
